import 'package:uuid/uuid.dart';
import 'package:vicyos_music/app/common/models/radio.stations.model.dart';

List<RadioStationInfo> radioStationList = <RadioStationInfo>[
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "A Rádio Rock",
    radioName: '89.0 FM • A Rádio Rock',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "89.0",
    radioUrl:
        'https://26653.live.streamtheworld.com/RADIO_89FM_ADP.aac?dist=site-89fm',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Band FM",
    radioName: 'Band FM 96,1',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "96.1",
    radioUrl:
        'https://playerservices.streamtheworld.com/api/livestream-redirect/BANDFM_SPAAC_SC',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Energia 97",
    radioName: 'Energia 97 | 97.7 FM',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "97.7",
    radioUrl: 'https://hela1.streaming.inweb.com.br/energia',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    // ratioStationLogo: "assets/img/radio_logos/metropolitana.png",
    radioSimpleName: "Metropolitana",
    radioName: 'Metropolitana FM 98.5',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "98.5",
    radioUrl: 'https://ice.fabricahost.com.br/metropolitana985sp',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Transamérica",
    radioName: 'Transamérica Pop 100.1 ',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "100.1",
    radioUrl:
        'https://playerservices.streamtheworld.com/api/livestream-redirect/RT_SP_SC',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Jovem Pam",
    radioName: 'Jovem Pam 100.9',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "100.9",
    radioUrl:
        'https://stream-165.zeno.fm/c45wbq2us3buv?zt=eyJhbGciOiJIUzI1NiJ9.eyJzdHJlYW0iOiJjNDV3YnEydXMzYnV2IiwiaG9zdCI6InN0cmVhbS0xNjUuemVuby5mbSIsInJ0dGwiOjUsImp0aSI6Ii1mS0FhNW5GUWJtQnJ1WnVCYVV0YnciLCJpYXQiOjE3NjI0NjA1NzksImV4cCI6MTc2MjQ2MDYzOX0.qZ6lxStUui4U9ISHMChoF7y36f5AqIkMYAbf0T0DIkQ',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Rádio Imprensa",
    radioName: 'Rádio Imprensa 102.5 FM',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "102.5",
    radioUrl: 'https://streaming.fox.srv.br:8048/stream/1/',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Dumont FM",
    radioName: '104.3 FM Dumont FM',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "104.3",
    radioUrl: 'https://rrdns-dumont.webnow.com.br/dumont.aac',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "105.1 FM",
    radioName: '105.1 FM ',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "105.1",
    radioUrl: 'https://www.appradio.app:8010/live',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "MIX FM",
    radioName: 'MIX FM 106.3',
    radioLocation: 'São Paulo • Brasil',
    radioStation: "106.3",
    radioUrl:
        'https://playerservices.streamtheworld.com/api/livestream-redirect/MIXFM_SAOPAULOAAC.aac?dist=mix-web-player-radio_player-ao-vivo&666061.3015838079',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "ABC NewsRadio",
    radioName: 'ABC NewsRadio',
    radioLocation: 'Sydney • Australia',
    radioStation: "ABC NewsRadio",
    radioUrl: 'https://abc.streamguys1.com/live/newsradio/icecast.audio',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "BBC Radio 3",
    radioName: 'BBC Radio 3',
    radioLocation: 'Mobile, Alabama • United States',
    radioStation: "BBC Radio 3",
    radioUrl: 'https://14223.live.streamtheworld.com/WUAL_HD3AAC.aac',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "BBC Radio 4",
    radioName: 'BBC Radio 4',
    radioLocation: 'London • United Kingdom',
    radioStation: "BBC Radio 4",
    radioUrl:
        'https://as-hls-ww-live.akamaized.net/pool_55057080/live/ww/bbc_radio_fourfm/bbc_radio_fourfm.isml/bbc_radio_fourfm-audio%3d96000.norewind.m3u8',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "LBC London News",
    radioName: 'LBC London News',
    radioLocation: 'London • United Kingdom',
    radioStation: "LBC London News",
    radioUrl: 'https://media-the.musicradio.com/LBC1152',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "KERA",
    radioName: 'KERA FM 90.1',
    radioLocation: 'Dallas, Texas • United States',
    radioStation: "90.1",
    radioUrl: 'https://kera-ice.streamguys1.com/keralive',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Trap Radio",
    radioName: 'Trap Radio',
    radioLocation: 'New York • United States',
    radioStation: "Trap Radio",
    radioUrl: 'https://skywatcherawakenedradio.radiolebowski.com/play',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "WBEZ",
    radioName: 'WBEZ • 91.5 Chicago Public Radio',
    radioLocation: 'Illinois • United States',
    radioStation: "91.5",
    radioUrl: 'https://stream.wbez.org/wbez64-web.aac',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Power",
    radioName: 'Radio Power 96.1 FM',
    radioLocation: "Atlanta's New Hit Music Station",
    radioStation: "96.1",
    radioUrl:
        'https://cloud.revma.ihrhls.com/zc741?rj-org=n46b-e2&rj-ttl=5&rj-tok=AAABmltjurgAx4D6FeIdvt02qQ',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "96.9",
    radioName: 'KLTA-HD2 96.9 - 96.9 Hits FM',
    radioLocation: 'Fargo, North Dakota • United States',
    radioStation: "96.9",
    radioUrl: 'https://ice9.securenetsystems.net/KLTAHD2',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Hot",
    radioName: 'Hot 97 FM',
    radioLocation: 'New York • United States',
    radioStation: "97",
    radioUrl:
        'https://18073.live.streamtheworld.com/WQHTFMAAC.aac?dist=triton-widget&tdsdk=js-2.9&swm=false&pname=tdwidgets&pversion=2.9&banners=none&gdpr=1&gdpr_consent=CQadvIAQadvIAAcABBENCDFgAAAAAAAAACiQAAAAAAAA.YAAAAAAAAAAA&burst-time=15&sbmid=8cb2228d-a549-46d7-c141-70d27b8b5386',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "KJ97",
    radioName: 'KJ97 KAJA 97,3',
    radioLocation: 'San Antonio, Texas • United States',
    radioStation: "97,3",
    radioUrl:
        'https://cloud.revma.ihrhls.com/zc2337?rj-org=n32b-e2&rj-ttl=5&rj-tok=AAABmp5GKeoAMzG96W3yUGpInQ',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "KMGO",
    radioName: 'KMGO FM 98.7',
    radioLocation: 'Centerville, Iowa • United States',
    radioStation: "98.7",
    radioUrl: 'https://us1.streamingpulse.com/ssl/987Kmgo',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "WKCN",
    radioName: 'Radio WKCN HD1 99.3 FM',
    radioLocation: 'Fort Benning South, Georgia • United States',
    radioStation: "99.3",
    radioUrl: 'https://ice66.securenetsystems.net/WKCNFM?1763595707425',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Hot Hitz",
    radioName: '100 Hitz - Hot Hitz',
    radioLocation: 'California • United States',
    radioStation: "100Hitz",
    radioUrl: 'https://pureplay.cdnstream1.com/6027_128.mp3',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "WHTZ Z100",
    radioName: 'WHTZ Z100 100.3 FM',
    radioLocation: 'New York • United States',
    radioStation: "100.3",
    radioUrl: 'https://stream.revma.ihrhls.com/zc1469?1762464240376',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Q102 Philly",
    radioName: 'Rádio Q102 Philly • 102.1 FM',
    radioLocation: "Philadelphia's Station for All the Hits",
    radioStation: "102.1",
    radioUrl: 'https://stream.revma.ihrhls.com/zc1997',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "KIIS",
    radioName: 'Radio KIIS 102.7 FM',
    radioLocation: 'Los Angeles, California • United States',
    radioStation: "102.7",
    radioUrl: 'https://stream.revma.ihrhls.com/zc185?1762467975628',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "102.9 NOW",
    radioName: '102.9 NOW',
    radioLocation: 'Dallas, Texas • United States',
    radioStation: "102.9",
    radioUrl:
        'https://cloud.revma.ihrhls.com/zc2237?rj-org=n0db-e2&rj-ttl=5&rj-tok=AAABmp5fzbIA_xxbyTJGo1EQ-g',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "KISS",
    radioName: '103.5 KISS FM',
    radioLocation: 'Chicago, Illinois • United States',
    radioStation: "103.5",
    radioUrl:
        'https://cloud.revma.ihrhls.com/zc849?rj-org=n01b-e2&rj-ttl=5&rj-tok=AAABmlt3m5sAGFL4am6uALnUow',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "WCRK",
    radioName: 'WCRK FM 105.7',
    radioLocation: 'Morristown, Tennessee • United States',
    radioStation: "105.7",
    radioUrl: 'https://ice41.securenetsystems.net/WCRK',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Jamz",
    radioName: 'Hot 108 Jamz',
    radioLocation: 'New York • United States',
    radioStation: "108",
    radioUrl: 'https://live.powerhitz.com/hot108?1762618514410',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "CHED",
    radioName: 'Radio CHED 630 AM',
    radioLocation: 'Edmonton, Alberta • Canada',
    radioStation: "630",
    radioUrl: 'https://live.leanstream.co/CHEDAM',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "CHQR",
    radioName: 'Radio CHQR 770 AM',
    radioLocation: 'Calgary, Alberta • Canada',
    radioStation: "770",
    radioUrl:
        'https://corus.leanstream.co/CHQRAM-MP3?type=.mp3&playertype=dplayer&DIST=TuneIn&TGT=TuneIn&maxServers=2&gdpr=0&us_privacy=1YYY&partnertok=eyJhbGciOiJIUzI1NiIsImtpZCI6InR1bmVpbiIsInR5cCI6IkpXVCJ9.eyJ0cnVzdGVkX3BhcnRuZXIiOnRydWUsImlhdCI6MTc2MjYxODI4NCwiaXNzIjoidGlzcNew YorkifQ.bVp1LgW_1PMJ_qheVVssDWbHWFkWQLv6K7C0xL4EWfM',
  ),
  RadioStationInfo(
    id: const Uuid().v4(),
    radioSimpleName: "Infowars",
    radioName: 'Infowars',
    radioLocation: 'Texas • United States',
    radioStation: "Infowars",
    radioUrl:
        'https://freespeech.akamaized.net/hls/live/2024573/live2/playlist-360.m3u8',
  ),
];
